osci-4645: add Errata Automation code
fedora-ci/ciboard pull request #127
Opened 2023-02-17 12:56 UTC by Andrei-Stepanov

@mgrabovsky this PR is ready for review and merge.

2023-02-20 14:44 UTC, mgrabovsky requested changes

2023-02-20 14:44 UTC, mgrabovsky commented on src/components/ArtifactDetailedInfo.tsx
> +import Linkify from 'linkify-react';
There are a couple of new unused imports here.

2023-02-20 14:44 UTC, mgrabovsky commented on src/types.ts
> +    /* Bugzilla bug numbe */
```suggestion
    /* Bugzilla bug number */
```

2023-02-20 14:44 UTC, mgrabovsky commented on src/types.ts
> +    /* What is the type of this bug from errata_automation POW */
```suggestion
    /* Type of bug from errata_automation point of view */
```

2023-02-20 14:44 UTC, mgrabovsky commented on src/types.ts
> +    msg_time: '2023-02-01T14:38:55.987655';
This is a weird type. Should it be `string` instead?

2023-02-20 14:44 UTC, mgrabovsky commented on src/components/ArtifactDetailedInfo.tsx
> +                    href={`${brokerMessage.ci_run_url}`}
This can be simply
```suggestion
                    href={brokerMessage.ci_run_url}
```

2023-02-20 14:44 UTC, mgrabovsky commented on src/components/ArtifactDetailedInfo.tsx
> +                    href={`${brokerMsgUrl}`}
```suggestion
                    href={brokerMsgUrl}
```

2023-02-20 14:44 UTC, mgrabovsky commented on src/components/ArtifactDetailedInfo.tsx
> +                    href={`${brokerMsgUrl}`}
Also, these links could use the `ExternalLink` component.

2023-02-20 14:44 UTC, mgrabovsky commented on src/components/ArtifactDetailedInfo.tsx
> +    ).toString();
Can you please factor this out to a separate function? It's already duplicated in [`ArtifactKaiState.tsx`](https://github.com/fedora-ci/ciboard/blob/e9c5371afa3733810ad80eecf3c3716401d976a0/src/components/ArtifactKaiState.tsx#L288-L291).

2023-02-20 14:44 UTC, mgrabovsky commented on src/components/ArtifactDetailedInfo.tsx
> +                    </a>
```suggestion
                    <ExternalLink href={`${config.et.url}/advisory/${bug.id}`}>
                        {bug.id}
                    </ExternalLink>
```

2023-02-20 14:51 UTC, mgrabovsky commented
Code looks fine, I've only suggested a couple of improvements. I'm not thrilled about the UI, but we can improve upon that later down the road.

2023-02-21 13:15 UTC, Andrei-Stepanov commented
@mgrabovsky update code.

2023-02-21 13:18 UTC, mgrabovsky approved these changes
Looks fine. Thanks for the changes.

2023-02-21 13:18 UTC, merged